/**
 * Generated by @skyleague/therefore@v1.0.0-local
 * Do not manually touch this
 */
/* eslint-disable */
import type { ValidateFunction } from 'ajv'

export type GetAllResponse = IdentificationDocumentTemplate[]

export const GetAllResponse = {
    validate: require('./schemas/get-all-response.schema.js') as ValidateFunction<GetAllResponse>,
    get schema() {
        return GetAllResponse.validate.schema
    },
    is: (o: unknown): o is GetAllResponse => GetAllResponse.validate(o) === true,
} as const

export interface ErrorResponse {
    errors?: RestError[]
}

export const ErrorResponse = {
    validate: require('./schemas/error-response.schema.js') as ValidateFunction<ErrorResponse>,
    get schema() {
        return ErrorResponse.validate.schema
    },
    is: (o: unknown): o is ErrorResponse => ErrorResponse.validate(o) === true,
} as const

/**
 * Template for identification documents
 */
export interface IdentificationDocumentTemplate {
    /**
     * The authority that issued the document
     */
    issuingAuthority?: string
    /**
     * The type of the document
     */
    documentType?: string
    /**
     * The encoded key of the identification document template, auto generated, unique
     */
    encodedKey?: string
    /**
     * Unique identifier for the template
     */
    id?: string
    /**
     * The document id template constraint, that contains letters (@) and digits (#) symbols used to validate the id
     */
    documentIdTemplate?: string
    /**
     * Whether this template is mandatory for individual clients or not
     */
    mandatory?: boolean
    /**
     * Whether this template allows attachments or not
     */
    allowAttachments?: boolean
}

export interface RestError {
    errorCode?: number
    errorSource?: string
    errorReason?: string
}
