/**
 * Generated by @skyleague/therefore@v1.0.0-local
 * Do not manually touch this
 */
/* eslint-disable */

import type { DefinedError, ValidateFunction } from 'ajv'

import { validate as BranchValidator } from './schemas/branch.schema.js'
import { validate as ErrorResponseValidator } from './schemas/error-response.schema.js'
import { validate as GetAllResponseValidator } from './schemas/get-all-response.schema.js'

/**
 * Represents an address.
 */
export interface Address {
    /**
     * The city for the address.
     */
    city?: string | undefined
    /**
     * The country.
     */
    country?: string | undefined
    /**
     * The address encoded key, which is unique and generated.
     */
    encodedKey?: string | undefined
    /**
     * The index of this address in the list of addresses.
     */
    indexInList?: number | undefined
    /**
     * The GPS latitude of this address in signed degrees format (DDD.dddd) with 6 decimal positions, ranging from -90 to +90.
     */
    latitude?: number | undefined
    /**
     * The first line of the address.
     */
    line1?: string | undefined
    /**
     * The second line of the address.
     */
    line2?: string | undefined
    /**
     * The GPS longitude of this address in signed degrees format (DDD.dddd) with 6 decimal positions, ranging from -180 to +180.
     */
    longitude?: number | undefined
    /**
     * The address parent key indicating the object owning this address. For example: client, centre, or branch.
     */
    parentKey?: string | undefined
    /**
     * The post code.
     */
    postcode?: string | undefined
    /**
     * The region for the address.
     */
    region?: string | undefined
}

export const Branch = {
    validate: BranchValidator as ValidateFunction<Branch>,
    get schema() {
        return Branch.validate.schema
    },
    get errors() {
        return Branch.validate.errors ?? undefined
    },
    is: (o: unknown): o is Branch => Branch.validate(o) === true,
    parse: (o: unknown): { right: Branch } | { left: DefinedError[] } => {
        if (Branch.is(o)) {
            return { right: o }
        }
        return { left: (Branch.errors ?? []) as DefinedError[] }
    },
} as const

/**
 * Represents a branch.
 */
export interface Branch {
    /**
     * The list of branch addresses.
     */
    addresses?: Address[] | undefined
    /**
     * The list of branch holidays.
     */
    branchHolidays?: Holiday[] | undefined
    /**
     * The creation date of the branch.
     */
    creationDate?: string | undefined
    /**
     * The branch email address.
     */
    emailAddress?: string | undefined
    /**
     * The encoded key of the entity, generated, globally unique
     */
    encodedKey?: string | undefined
    /**
     * The branch ID, which must be unique.
     */
    id: string
    /**
     * The last date when the branch was modified.
     */
    lastModifiedDate?: string | undefined
    /**
     * The branch name.
     */
    name: string
    /**
     * The notes or description attached to this object.
     */
    notes?: string | undefined
    /**
     * The branch phone number.
     */
    phoneNumber?: string | undefined
    /**
     * The branch state.
     */
    state?: 'ACTIVE' | 'INACTIVE' | undefined
}

export const ErrorResponse = {
    validate: ErrorResponseValidator as ValidateFunction<ErrorResponse>,
    get schema() {
        return ErrorResponse.validate.schema
    },
    get errors() {
        return ErrorResponse.validate.errors ?? undefined
    },
    is: (o: unknown): o is ErrorResponse => ErrorResponse.validate(o) === true,
    parse: (o: unknown): { right: ErrorResponse } | { left: DefinedError[] } => {
        if (ErrorResponse.is(o)) {
            return { right: o }
        }
        return { left: (ErrorResponse.errors ?? []) as DefinedError[] }
    },
} as const

export interface ErrorResponse {
    errors?: RestError[] | undefined
}

export const GetAllResponse = {
    validate: GetAllResponseValidator as ValidateFunction<GetAllResponse>,
    get schema() {
        return GetAllResponse.validate.schema
    },
    get errors() {
        return GetAllResponse.validate.errors ?? undefined
    },
    is: (o: unknown): o is GetAllResponse => GetAllResponse.validate(o) === true,
    parse: (o: unknown): { right: GetAllResponse } | { left: DefinedError[] } => {
        if (GetAllResponse.is(o)) {
            return { right: o }
        }
        return { left: (GetAllResponse.errors ?? []) as DefinedError[] }
    },
} as const

export type GetAllResponse = Branch[]

/**
 * Represents the holiday.
 */
export interface Holiday {
    /**
     * The date when the holiday was created.
     */
    creationDate?: string | undefined
    /**
     * The date the holiday takes place.
     */
    date?: string | undefined
    /**
     * The encoded key of the entity, generated, globally unique
     */
    encodedKey?: string | undefined
    /**
     * The ID of the holiday.
     */
    id?: number | undefined
    /**
     * `TRUE` if a holiday is annually recurring, `FALSE` otherwise.
     */
    isAnnuallyRecurring?: boolean | undefined
    /**
     * The name of the holiday.
     */
    name?: string | undefined
}

export interface RestError {
    errorCode?: number | undefined
    errorReason?: string | undefined
    errorSource?: string | undefined
}
